services:
  backend:
    build: ./backend
    container_name: BE
    restart: unless-stopped
    depends_on:
      - mongo
    environment:
      APP_PORT: "${APP_PORT}"
      MONGO_URI: "${MONGO_URI}"
      JWT_SECRET: ${JWT_SECRET}
      GEMINI_KEY : ${GEMINI_KEY}
    ports:
      - 4000:4000
    networks:
      - hass-net  
  frontend:
    build: ./frontend
    container_name: FE
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - 3000:3000
    networks:
      - hass-net      
  mongo:
    image: mongo:latest
    container_name: mongodb
    restart: unless-stopped
    volumes:
      - ./XSTORAGE/mongodb:/data/db
    networks:
      - hass-net    
networks:
  hass-net:
    driver: host
